### ISSUE TITLE
设备类型和项目打开运行

### ISSUE THREAD

**Issue by zerosnsa** [LHC324/pax_priva#1]
**请问有具体的设备连接信息吗，项目直接打开的话会出现z'x这些错误是怎么回事呢
![1710729673255](https://github.com/LHC324/pax_priva/assets/152005489/5ba49a23-32a1-441d-8a69-cba1ada589ab)

**Comment by LHC324** [comment]
> **请问有具体的设备连接信息吗，项目直接打开的话会出现z'x这些错误是怎么回事呢 ![1710729673255](https://private-user-images.githubusercontent.com/152005489/313533657-5ba49a23-32a1-441d-8a69-cba1ada589ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NjI2NzgsIm5iZiI6MTcxMDc2MjM3OCwicGF0aCI6Ii8xNTIwMDU0ODkvMzEzNTMzNjU3LTViYTQ5YTIzLTMyYTEtNDQxZC04YTY5LWNiYTFhZGE1ODlhYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOFQxMTQ2MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMTI3MjZlM2Y3NGQ3MzYzOTQ2YzYzNWUyOWUzYzcwMDk1Y2M4MjJjNGUyMTRiYmU4YWE5ZGMwYmQxMjNlMmIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2P0O8NtBQOIFwZ3-0LHrP9At-E_DMbOzXuOmJ_WBBrg)

把报错的地方截图出来看下，你这个看不到具体错误

**Comment by zerosnsa** [comment]
这个是全部编译之后显示的错误信息，你使用的是keil5吗，有些文件路径不正确
![1710814983580](https://github.com/LHC324/pax_priva/assets/152005489/6fd9d97c-15b2-48d1-9caa-fd6db3c8fba4)

**Comment by LHC324** [comment]
> 这个是全部编译之后显示的错误信息，你使用的是keil5吗，有些文件路径不正确 ![1710814983580](https://private-user-images.githubusercontent.com/152005489/313892687-6fd9d97c-15b2-48d1-9caa-fd6db3c8fba4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4NTQ3MTUsIm5iZiI6MTcxMDg1NDQxNSwicGF0aCI6Ii8xNTIwMDU0ODkvMzEzODkyNjg3LTZmZDlkOTdjLTE1YjItNDhkMS05Y2FhLWZkNmRiM2M4ZmJhNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOVQxMzIwMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MDgwZGQ1NzgyNjVmZmFhMDE3MGM4ODM3MGE5OWJhOGU4YWZiMjJjMjgzNWRiYjliMmUzN2RmYWFlY2E2ZmNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Xm6eL9oitxMkqqgMo1-8UuPb0Hcvdzle_k6upWiFO4Y)

不是路径的问题，另外这个使用keil 5 和直接使用rtthread 的env gcc编译都是可以的，你这个错误是因为我默认使用的是rtthread的包管理工具，会自动拉取缺少的包，lfs是一个文件系统，推荐你使用env工具重新配置一下工程
![image](https://github.com/LHC324/pax_priva/assets/66255985/4695a080-71f0-416c-bb7e-f54efd080c84)

**Comment by zerosnsa** [comment]
那请问你使用的传感器和其他的外设有具体的型号和连接方式吗

**Comment by LHC324** [comment]
> 那请问你使用的传感器和其他的外设有具体的型号和连接方式吗

系统接入的是电流4-20ma和电压：0-10v设备，或者485通讯设备，不需要指定具体的传感器型号，通用标准。
